// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

let DATABASE_URL: string;

if (process.env["NODE_ENV"] === "test") {
  if (process.env["TEST_DATABASE_URL"]) {
    DATABASE_URL = process.env["TEST_DATABASE_URL"];
  } else {
    throw new Error(
      "TEST_DATABASE_URL environment variable is not set for test environment",
    );
  }
} else {
  if (process.env["DATABASE_URL"]) {
    DATABASE_URL = process.env["DATABASE_URL"];
  } else {
    throw new Error(
      "DATABASE_URL environment variable is not set for non-test environment",
    );
  }
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: DATABASE_URL,
  },
});
