name: Lint and Type Check

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main
env:
  DATABASE_URL: postgresql://test_user:test_password@localhost:5432/postgres_db
jobs:
  lint:
    runs-on: ubuntu-latest
    name: Run lint check

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Node.js 24
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: npm

      - name: Install dependencies
        run: npm run install:all

      - name: Generate Prisma client
        run: npm run db:generate

      - name: Lint webapp
        run: npm run lint:webapp

      - name: Lint server
        run: npm run lint:server

  type_check:
    runs-on: ubuntu-latest
    name: Run type-check

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Node.js 24
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: npm

      - name: Install dependencies
        run: npm run install:all

      - name: Generate Prisma client
        run: npm run db:generate

      - name: Type check webapp
        run: npm run typecheck:webapp

      - name: Type check server
        run: npm run typecheck:server
